title: "Cycle.js"
author: "Andre Staltz"
description: "The Worlds first Cycle.js Conference in Copenhagen 22nd of April – 24th of April"
more: "read more"
url: "http://cycle.js.org/"
permalink: "/"

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "blank"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
gems:
  - octopress-autoprefixer
  - kramdown
